#! /bin/bash

service rsyslog start
/opt/graphite/bin/carbon-daemon.py writer-1 start
#/opt/graphite/bin/carbon-daemon.py writer-2 start
/opt/graphite/bin/carbon-daemon.py relay start
nohup /usr/bin/django-admin runserver --pythonpath /opt/graphite/webapp --settings graphite.settings 127.0.0.1:3031 &
service nginx start

